# coding: utf-8

"""
    OpenSubtitles API

    Explore Open Subtitles API here

    The version of the OpenAPI document: 1.0.1
    Contact: support@opensubtitles.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class Download200Response(BaseModel):
    """
    
    """ # noqa: E501
    link: Annotated[str, Field(min_length=1, strict=True)]
    file_name: Annotated[str, Field(min_length=1, strict=True)]
    requests: Union[StrictFloat, StrictInt]
    remaining: Union[StrictFloat, StrictInt]
    message: Annotated[str, Field(min_length=1, strict=True)]
    reset_time: Annotated[str, Field(min_length=1, strict=True)]
    reset_time_utc: Annotated[str, Field(min_length=1, strict=True)]
    __properties: ClassVar[List[str]] = ["link", "file_name", "requests", "remaining", "message", "reset_time", "reset_time_utc"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Download200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Download200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "link": obj.get("link"),
            "file_name": obj.get("file_name"),
            "requests": obj.get("requests"),
            "remaining": obj.get("remaining"),
            "message": obj.get("message"),
            "reset_time": obj.get("reset_time"),
            "reset_time_utc": obj.get("reset_time_utc")
        })
        return _obj


