# coding: utf-8

"""
    OpenSubtitles API

    Explore Open Subtitles API here

    The version of the OpenAPI document: 1.0.1
    Contact: support@opensubtitles.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class DownloadRequest(BaseModel):
    """
    DownloadRequest
    """ # noqa: E501
    file_id: StrictInt = Field(description="file_id from /subtitles search results")
    sub_format: Optional[StrictStr] = Field(default=None, description="from /infos/formats")
    file_name: Optional[StrictStr] = Field(default=None, description="desired file name")
    in_fps: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="used for conversions, in_fps and out_fps must then be indicated")
    out_fps: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="used for conversions, in_fps and out_fps must then be indicated")
    timeshift: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="delay to add or remove to the subtitle, + or - value, in seconds, i.e. 2.5s or -1s ")
    force_download: Optional[StrictBool] = Field(default=None, description="(1/0) set subtitle file headers to \"application/force-download\"")
    __properties: ClassVar[List[str]] = ["file_id", "sub_format", "file_name", "in_fps", "out_fps", "timeshift", "force_download"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DownloadRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DownloadRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "file_id": obj.get("file_id"),
            "sub_format": obj.get("sub_format"),
            "file_name": obj.get("file_name"),
            "in_fps": obj.get("in_fps"),
            "out_fps": obj.get("out_fps"),
            "timeshift": obj.get("timeshift"),
            "force_download": obj.get("force_download")
        })
        return _obj


