# coding: utf-8

"""
    OpenSubtitles API

    Explore Open Subtitles API here

    The version of the OpenAPI document: 1.0.1
    Contact: support@opensubtitles.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from opensubtitles_client.models.feature_tvshow_attributes_seasons_inner_episodes_inner import FeatureTvshowAttributesSeasonsInnerEpisodesInner
from typing import Optional, Set
from typing_extensions import Self

class FeatureTvshowAttributesSeasonsInner(BaseModel):
    """
    FeatureTvshowAttributesSeasonsInner
    """ # noqa: E501
    season_number: Union[StrictFloat, StrictInt]
    episodes: Optional[Annotated[List[FeatureTvshowAttributesSeasonsInnerEpisodesInner], Field(min_length=1)]] = None
    __properties: ClassVar[List[str]] = ["season_number", "episodes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FeatureTvshowAttributesSeasonsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in episodes (list)
        _items = []
        if self.episodes:
            for _item_episodes in self.episodes:
                if _item_episodes:
                    _items.append(_item_episodes.to_dict())
            _dict['episodes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FeatureTvshowAttributesSeasonsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "season_number": obj.get("season_number"),
            "episodes": [FeatureTvshowAttributesSeasonsInnerEpisodesInner.from_dict(_item) for _item in obj["episodes"]] if obj.get("episodes") is not None else None
        })
        return _obj


