# coding: utf-8

"""
    OpenSubtitles API

    Explore Open Subtitles API here

    The version of the OpenAPI document: 1.0.1
    Contact: support@opensubtitles.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class FeatureMovieAttributesSubtitlesCounts(BaseModel):
    """
    FeatureMovieAttributesSubtitlesCounts
    """ # noqa: E501
    en: Union[StrictFloat, StrictInt]
    pt_pt: Union[StrictFloat, StrictInt] = Field(alias="pt-PT")
    fi: Union[StrictFloat, StrictInt]
    pt_br: Union[StrictFloat, StrictInt] = Field(alias="pt-BR")
    es: Union[StrictFloat, StrictInt]
    ar: Union[StrictFloat, StrictInt]
    pl: Union[StrictFloat, StrictInt]
    sr: Union[StrictFloat, StrictInt]
    id: Union[StrictFloat, StrictInt]
    ro: Union[StrictFloat, StrictInt]
    zh_cn: Union[StrictFloat, StrictInt] = Field(alias="zh-CN")
    nl: Union[StrictFloat, StrictInt]
    el: Union[StrictFloat, StrictInt]
    hu: Union[StrictFloat, StrictInt]
    fr: Union[StrictFloat, StrictInt]
    sl: Union[StrictFloat, StrictInt]
    tr: Union[StrictFloat, StrictInt]
    et: Union[StrictFloat, StrictInt]
    bg: Union[StrictFloat, StrictInt]
    cs: Union[StrictFloat, StrictInt]
    de: Union[StrictFloat, StrictInt]
    he: Union[StrictFloat, StrictInt]
    it: Union[StrictFloat, StrictInt]
    vi: Union[StrictFloat, StrictInt]
    hr: Union[StrictFloat, StrictInt]
    ko: Union[StrictFloat, StrictInt]
    no: Union[StrictFloat, StrictInt]
    sv: Union[StrictFloat, StrictInt]
    ta: Union[StrictFloat, StrictInt]
    eu: Union[StrictFloat, StrictInt]
    da: Union[StrictFloat, StrictInt]
    fa: Union[StrictFloat, StrictInt]
    sk: Union[StrictFloat, StrictInt]
    uk: Union[StrictFloat, StrictInt]
    zh_tw: Union[StrictFloat, StrictInt] = Field(alias="zh-TW")
    bn: Union[StrictFloat, StrictInt]
    ka: Union[StrictFloat, StrictInt]
    ja: Union[StrictFloat, StrictInt]
    lt: Union[StrictFloat, StrictInt]
    mk: Union[StrictFloat, StrictInt]
    ml: Union[StrictFloat, StrictInt]
    ms: Union[StrictFloat, StrictInt]
    ru: Union[StrictFloat, StrictInt]
    ze: Union[StrictFloat, StrictInt]
    __properties: ClassVar[List[str]] = ["en", "pt-PT", "fi", "pt-BR", "es", "ar", "pl", "sr", "id", "ro", "zh-CN", "nl", "el", "hu", "fr", "sl", "tr", "et", "bg", "cs", "de", "he", "it", "vi", "hr", "ko", "no", "sv", "ta", "eu", "da", "fa", "sk", "uk", "zh-TW", "bn", "ka", "ja", "lt", "mk", "ml", "ms", "ru", "ze"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FeatureMovieAttributesSubtitlesCounts from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FeatureMovieAttributesSubtitlesCounts from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "en": obj.get("en"),
            "pt-PT": obj.get("pt-PT"),
            "fi": obj.get("fi"),
            "pt-BR": obj.get("pt-BR"),
            "es": obj.get("es"),
            "ar": obj.get("ar"),
            "pl": obj.get("pl"),
            "sr": obj.get("sr"),
            "id": obj.get("id"),
            "ro": obj.get("ro"),
            "zh-CN": obj.get("zh-CN"),
            "nl": obj.get("nl"),
            "el": obj.get("el"),
            "hu": obj.get("hu"),
            "fr": obj.get("fr"),
            "sl": obj.get("sl"),
            "tr": obj.get("tr"),
            "et": obj.get("et"),
            "bg": obj.get("bg"),
            "cs": obj.get("cs"),
            "de": obj.get("de"),
            "he": obj.get("he"),
            "it": obj.get("it"),
            "vi": obj.get("vi"),
            "hr": obj.get("hr"),
            "ko": obj.get("ko"),
            "no": obj.get("no"),
            "sv": obj.get("sv"),
            "ta": obj.get("ta"),
            "eu": obj.get("eu"),
            "da": obj.get("da"),
            "fa": obj.get("fa"),
            "sk": obj.get("sk"),
            "uk": obj.get("uk"),
            "zh-TW": obj.get("zh-TW"),
            "bn": obj.get("bn"),
            "ka": obj.get("ka"),
            "ja": obj.get("ja"),
            "lt": obj.get("lt"),
            "mk": obj.get("mk"),
            "ml": obj.get("ml"),
            "ms": obj.get("ms"),
            "ru": obj.get("ru"),
            "ze": obj.get("ze")
        })
        return _obj


