# coding: utf-8

"""
    OpenSubtitles API

    Explore Open Subtitles API here

    The version of the OpenAPI document: 1.0.1
    Contact: support@opensubtitles.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class FeatureEpisodeAttributesSubtitlesCounts(BaseModel):
    """
    FeatureEpisodeAttributesSubtitlesCounts
    """ # noqa: E501
    pl: Union[StrictFloat, StrictInt]
    en: Union[StrictFloat, StrictInt]
    pt_br: Union[StrictFloat, StrictInt] = Field(alias="pt-BR")
    es: Union[StrictFloat, StrictInt]
    ro: Union[StrictFloat, StrictInt]
    nl: Union[StrictFloat, StrictInt]
    tr: Union[StrictFloat, StrictInt]
    he: Union[StrictFloat, StrictInt]
    pt_pt: Union[StrictFloat, StrictInt] = Field(alias="pt-PT")
    cs: Union[StrictFloat, StrictInt]
    fi: Union[StrictFloat, StrictInt]
    hu: Union[StrictFloat, StrictInt]
    ar: Union[StrictFloat, StrictInt]
    bg: Union[StrictFloat, StrictInt]
    fr: Union[StrictFloat, StrictInt]
    sl: Union[StrictFloat, StrictInt]
    el: Union[StrictFloat, StrictInt]
    hr: Union[StrictFloat, StrictInt]
    sr: Union[StrictFloat, StrictInt]
    et: Union[StrictFloat, StrictInt]
    sv: Union[StrictFloat, StrictInt]
    th: Union[StrictFloat, StrictInt]
    bs: Union[StrictFloat, StrictInt]
    da: Union[StrictFloat, StrictInt]
    de: Union[StrictFloat, StrictInt]
    mk: Union[StrictFloat, StrictInt]
    no: Union[StrictFloat, StrictInt]
    ru: Union[StrictFloat, StrictInt]
    __properties: ClassVar[List[str]] = ["pl", "en", "pt-BR", "es", "ro", "nl", "tr", "he", "pt-PT", "cs", "fi", "hu", "ar", "bg", "fr", "sl", "el", "hr", "sr", "et", "sv", "th", "bs", "da", "de", "mk", "no", "ru"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FeatureEpisodeAttributesSubtitlesCounts from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FeatureEpisodeAttributesSubtitlesCounts from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "pl": obj.get("pl"),
            "en": obj.get("en"),
            "pt-BR": obj.get("pt-BR"),
            "es": obj.get("es"),
            "ro": obj.get("ro"),
            "nl": obj.get("nl"),
            "tr": obj.get("tr"),
            "he": obj.get("he"),
            "pt-PT": obj.get("pt-PT"),
            "cs": obj.get("cs"),
            "fi": obj.get("fi"),
            "hu": obj.get("hu"),
            "ar": obj.get("ar"),
            "bg": obj.get("bg"),
            "fr": obj.get("fr"),
            "sl": obj.get("sl"),
            "el": obj.get("el"),
            "hr": obj.get("hr"),
            "sr": obj.get("sr"),
            "et": obj.get("et"),
            "sv": obj.get("sv"),
            "th": obj.get("th"),
            "bs": obj.get("bs"),
            "da": obj.get("da"),
            "de": obj.get("de"),
            "mk": obj.get("mk"),
            "no": obj.get("no"),
            "ru": obj.get("ru")
        })
        return _obj


