# coding: utf-8

"""
    OpenSubtitles API

    Explore Open Subtitles API here

    The version of the OpenAPI document: 1.0.1
    Contact: support@opensubtitles.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from opensubtitles_client.models.feature_tvshow_attributes_seasons_inner import FeatureTvshowAttributesSeasonsInner
from opensubtitles_client.models.feature_tvshow_attributes_subtitles_counts import FeatureTvshowAttributesSubtitlesCounts
from typing import Optional, Set
from typing_extensions import Self

class FeatureTvshowAttributes(BaseModel):
    """
    FeatureTvshowAttributes
    """ # noqa: E501
    title: Annotated[str, Field(min_length=1, strict=True)]
    original_title: Annotated[str, Field(min_length=1, strict=True)]
    year: Annotated[str, Field(min_length=1, strict=True)]
    imdb_id: Union[StrictFloat, StrictInt]
    tmdb_id: Union[StrictFloat, StrictInt]
    title_aka: List[Dict[str, Any]]
    feature_id: Annotated[str, Field(min_length=1, strict=True)]
    url: Annotated[str, Field(min_length=1, strict=True)]
    img_url: Annotated[str, Field(min_length=1, strict=True)]
    subtitles_counts: FeatureTvshowAttributesSubtitlesCounts
    subtitles_count: Union[StrictFloat, StrictInt]
    seasons: Annotated[List[FeatureTvshowAttributesSeasonsInner], Field(min_length=1)]
    __properties: ClassVar[List[str]] = ["title", "original_title", "year", "imdb_id", "tmdb_id", "title_aka", "feature_id", "url", "img_url", "subtitles_counts", "subtitles_count", "seasons"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FeatureTvshowAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of subtitles_counts
        if self.subtitles_counts:
            _dict['subtitles_counts'] = self.subtitles_counts.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in seasons (list)
        _items = []
        if self.seasons:
            for _item_seasons in self.seasons:
                if _item_seasons:
                    _items.append(_item_seasons.to_dict())
            _dict['seasons'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FeatureTvshowAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "original_title": obj.get("original_title"),
            "year": obj.get("year"),
            "imdb_id": obj.get("imdb_id"),
            "tmdb_id": obj.get("tmdb_id"),
            "title_aka": obj.get("title_aka"),
            "feature_id": obj.get("feature_id"),
            "url": obj.get("url"),
            "img_url": obj.get("img_url"),
            "subtitles_counts": FeatureTvshowAttributesSubtitlesCounts.from_dict(obj["subtitles_counts"]) if obj.get("subtitles_counts") is not None else None,
            "subtitles_count": obj.get("subtitles_count"),
            "seasons": [FeatureTvshowAttributesSeasonsInner.from_dict(_item) for _item in obj["seasons"]] if obj.get("seasons") is not None else None
        })
        return _obj


