# coding: utf-8

"""
    OpenSubtitles API

    Explore Open Subtitles API here

    The version of the OpenAPI document: 1.0.1
    Contact: support@opensubtitles.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from opensubtitles_client.models.login200_response_user import Login200ResponseUser
from typing import Optional, Set
from typing_extensions import Self

class Login200Response(BaseModel):
    """
    Login200Response
    """ # noqa: E501
    user: Login200ResponseUser
    base_url: StrictStr
    token: Annotated[str, Field(min_length=1, strict=True)]
    status: Union[StrictFloat, StrictInt]
    __properties: ClassVar[List[str]] = ["user", "base_url", "token", "status"]

    @field_validator('base_url')
    def base_url_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['api.opensubtitles.com', 'vip-api.opensubtitles.com']):
            raise ValueError("must be one of enum values ('api.opensubtitles.com', 'vip-api.opensubtitles.com')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Login200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Login200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user": Login200ResponseUser.from_dict(obj["user"]) if obj.get("user") is not None else None,
            "base_url": obj.get("base_url") if obj.get("base_url") is not None else 'api.opensubtitles.com',
            "token": obj.get("token"),
            "status": obj.get("status")
        })
        return _obj


