# coding: utf-8

"""
    OpenSubtitles API

    Explore Open Subtitles API here

    The version of the OpenAPI document: 1.0.1
    Contact: support@opensubtitles.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class Login200ResponseUser(BaseModel):
    """
    Login200ResponseUser
    """ # noqa: E501
    allowed_translations: Union[StrictFloat, StrictInt]
    allowed_downloads: Union[StrictFloat, StrictInt]
    level: Annotated[str, Field(min_length=1, strict=True)]
    user_id: Union[StrictFloat, StrictInt]
    ext_installed: StrictBool
    vip: StrictBool
    __properties: ClassVar[List[str]] = ["allowed_translations", "allowed_downloads", "level", "user_id", "ext_installed", "vip"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Login200ResponseUser from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Login200ResponseUser from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allowed_translations": obj.get("allowed_translations"),
            "allowed_downloads": obj.get("allowed_downloads"),
            "level": obj.get("level"),
            "user_id": obj.get("user_id"),
            "ext_installed": obj.get("ext_installed"),
            "vip": obj.get("vip")
        })
        return _obj


