# coding: utf-8

"""
    OpenSubtitles API

    Explore Open Subtitles API here

    The version of the OpenAPI document: 1.0.1
    Contact: support@opensubtitles.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Subtitles200ResponseDataInnerAttributesFeatureDetails(BaseModel):
    """
    Subtitles200ResponseDataInnerAttributesFeatureDetails
    """ # noqa: E501
    feature_id: Optional[StrictInt] = None
    feature_type: Optional[StrictStr] = None
    year: Optional[StrictInt] = None
    title: Optional[StrictStr] = None
    movie_name: Optional[StrictStr] = None
    imdb_id: Optional[StrictInt] = None
    tmdb_id: Optional[StrictInt] = None
    season_number: Optional[StrictInt] = None
    episode_number: Optional[StrictInt] = None
    parent_imdb_id: Optional[StrictInt] = None
    parent_title: Optional[StrictStr] = None
    parent_tmdb_id: Optional[StrictInt] = None
    parent_feature_id: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["feature_id", "feature_type", "year", "title", "movie_name", "imdb_id", "tmdb_id", "season_number", "episode_number", "parent_imdb_id", "parent_title", "parent_tmdb_id", "parent_feature_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Subtitles200ResponseDataInnerAttributesFeatureDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Subtitles200ResponseDataInnerAttributesFeatureDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "feature_id": obj.get("feature_id"),
            "feature_type": obj.get("feature_type"),
            "year": obj.get("year"),
            "title": obj.get("title"),
            "movie_name": obj.get("movie_name"),
            "imdb_id": obj.get("imdb_id"),
            "tmdb_id": obj.get("tmdb_id"),
            "season_number": obj.get("season_number"),
            "episode_number": obj.get("episode_number"),
            "parent_imdb_id": obj.get("parent_imdb_id"),
            "parent_title": obj.get("parent_title"),
            "parent_tmdb_id": obj.get("parent_tmdb_id"),
            "parent_feature_id": obj.get("parent_feature_id")
        })
        return _obj


