# coding: utf-8

"""
    OpenSubtitles API

    Explore Open Subtitles API here

    The version of the OpenAPI document: 1.0.1
    Contact: support@opensubtitles.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from opensubtitles_client.models.subtitle_attributes_feature_details import SubtitleAttributesFeatureDetails
from opensubtitles_client.models.subtitle_attributes_files_inner import SubtitleAttributesFilesInner
from opensubtitles_client.models.subtitle_attributes_uploader import SubtitleAttributesUploader
from typing import Optional, Set
from typing_extensions import Self

class SubtitleAttributes(BaseModel):
    """
    SubtitleAttributes
    """ # noqa: E501
    subtitle_id: Annotated[str, Field(min_length=1, strict=True)]
    language: Annotated[str, Field(min_length=1, strict=True)]
    download_count: Union[StrictFloat, StrictInt]
    new_download_count: Union[StrictFloat, StrictInt]
    hearing_impaired: Optional[StrictBool] = None
    hd: Optional[StrictBool] = None
    fps: Optional[Union[StrictFloat, StrictInt]] = None
    votes: Optional[Union[StrictFloat, StrictInt]] = None
    points: Optional[Union[StrictFloat, StrictInt]] = None
    ratings: Optional[Union[StrictFloat, StrictInt]] = None
    from_trusted: StrictBool
    foreign_parts_only: StrictBool
    ai_translated: StrictBool
    machine_translated: StrictBool
    upload_date: Annotated[str, Field(min_length=1, strict=True)]
    release: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    comments: Optional[StrictStr] = None
    legacy_subtitle_id: Optional[Union[StrictFloat, StrictInt]] = None
    uploader: Optional[SubtitleAttributesUploader] = None
    feature_details: SubtitleAttributesFeatureDetails
    url: Annotated[str, Field(min_length=1, strict=True)]
    related_links: Optional[List[Dict[str, Any]]] = None
    files: Annotated[List[SubtitleAttributesFilesInner], Field(min_length=1)]
    __properties: ClassVar[List[str]] = ["subtitle_id", "language", "download_count", "new_download_count", "hearing_impaired", "hd", "fps", "votes", "points", "ratings", "from_trusted", "foreign_parts_only", "ai_translated", "machine_translated", "upload_date", "release", "comments", "legacy_subtitle_id", "uploader", "feature_details", "url", "related_links", "files"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubtitleAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of uploader
        if self.uploader:
            _dict['uploader'] = self.uploader.to_dict()
        # override the default output from pydantic by calling `to_dict()` of feature_details
        if self.feature_details:
            _dict['feature_details'] = self.feature_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in files (list)
        _items = []
        if self.files:
            for _item_files in self.files:
                if _item_files:
                    _items.append(_item_files.to_dict())
            _dict['files'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubtitleAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "subtitle_id": obj.get("subtitle_id"),
            "language": obj.get("language"),
            "download_count": obj.get("download_count"),
            "new_download_count": obj.get("new_download_count"),
            "hearing_impaired": obj.get("hearing_impaired"),
            "hd": obj.get("hd"),
            "fps": obj.get("fps"),
            "votes": obj.get("votes"),
            "points": obj.get("points"),
            "ratings": obj.get("ratings"),
            "from_trusted": obj.get("from_trusted"),
            "foreign_parts_only": obj.get("foreign_parts_only"),
            "ai_translated": obj.get("ai_translated"),
            "machine_translated": obj.get("machine_translated"),
            "upload_date": obj.get("upload_date"),
            "release": obj.get("release"),
            "comments": obj.get("comments"),
            "legacy_subtitle_id": obj.get("legacy_subtitle_id"),
            "uploader": SubtitleAttributesUploader.from_dict(obj["uploader"]) if obj.get("uploader") is not None else None,
            "feature_details": SubtitleAttributesFeatureDetails.from_dict(obj["feature_details"]) if obj.get("feature_details") is not None else None,
            "url": obj.get("url"),
            "related_links": obj.get("related_links"),
            "files": [SubtitleAttributesFilesInner.from_dict(_item) for _item in obj["files"]] if obj.get("files") is not None else None
        })
        return _obj


