# coding: utf-8

"""
    OpenSubtitles API

    Explore Open Subtitles API here

    The version of the OpenAPI document: 1.0.1
    Contact: support@opensubtitles.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from opensubtitles_client.models.subtitles200_response_data_inner_attributes_feature_details import Subtitles200ResponseDataInnerAttributesFeatureDetails
from opensubtitles_client.models.subtitles200_response_data_inner_attributes_files_inner import Subtitles200ResponseDataInnerAttributesFilesInner
from opensubtitles_client.models.subtitles200_response_data_inner_attributes_related_links_inner import Subtitles200ResponseDataInnerAttributesRelatedLinksInner
from opensubtitles_client.models.subtitles200_response_data_inner_attributes_uploader import Subtitles200ResponseDataInnerAttributesUploader
from typing import Optional, Set
from typing_extensions import Self

class Subtitles200ResponseDataInnerAttributes(BaseModel):
    """
    Subtitles200ResponseDataInnerAttributes
    """ # noqa: E501
    subtitle_id: Optional[StrictStr] = None
    language: Optional[StrictStr] = None
    download_count: Optional[StrictInt] = None
    new_download_count: Optional[StrictInt] = None
    hearing_impaired: Optional[StrictBool] = None
    hd: Optional[StrictBool] = None
    fps: Optional[Union[StrictFloat, StrictInt]] = None
    votes: Optional[StrictInt] = None
    ratings: Optional[StrictInt] = None
    from_trusted: Optional[StrictBool] = None
    foreign_parts_only: Optional[StrictBool] = None
    upload_date: Optional[StrictStr] = None
    ai_translated: Optional[StrictBool] = None
    nb_cd: Optional[StrictInt] = None
    slug: Optional[StrictStr] = None
    machine_translated: Optional[StrictBool] = None
    release: Optional[StrictStr] = None
    comments: Optional[StrictStr] = None
    legacy_subtitle_id: Optional[StrictInt] = None
    legacy_uploader_id: Optional[StrictInt] = None
    uploader: Optional[Subtitles200ResponseDataInnerAttributesUploader] = None
    feature_details: Optional[Subtitles200ResponseDataInnerAttributesFeatureDetails] = None
    url: Optional[StrictStr] = None
    related_links: Optional[List[Subtitles200ResponseDataInnerAttributesRelatedLinksInner]] = None
    files: Optional[List[Subtitles200ResponseDataInnerAttributesFilesInner]] = None
    __properties: ClassVar[List[str]] = ["subtitle_id", "language", "download_count", "new_download_count", "hearing_impaired", "hd", "fps", "votes", "ratings", "from_trusted", "foreign_parts_only", "upload_date", "ai_translated", "nb_cd", "slug", "machine_translated", "release", "comments", "legacy_subtitle_id", "legacy_uploader_id", "uploader", "feature_details", "url", "related_links", "files"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Subtitles200ResponseDataInnerAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of uploader
        if self.uploader:
            _dict['uploader'] = self.uploader.to_dict()
        # override the default output from pydantic by calling `to_dict()` of feature_details
        if self.feature_details:
            _dict['feature_details'] = self.feature_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in related_links (list)
        _items = []
        if self.related_links:
            for _item_related_links in self.related_links:
                if _item_related_links:
                    _items.append(_item_related_links.to_dict())
            _dict['related_links'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in files (list)
        _items = []
        if self.files:
            for _item_files in self.files:
                if _item_files:
                    _items.append(_item_files.to_dict())
            _dict['files'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Subtitles200ResponseDataInnerAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "subtitle_id": obj.get("subtitle_id"),
            "language": obj.get("language"),
            "download_count": obj.get("download_count"),
            "new_download_count": obj.get("new_download_count"),
            "hearing_impaired": obj.get("hearing_impaired"),
            "hd": obj.get("hd"),
            "fps": obj.get("fps"),
            "votes": obj.get("votes"),
            "ratings": obj.get("ratings"),
            "from_trusted": obj.get("from_trusted"),
            "foreign_parts_only": obj.get("foreign_parts_only"),
            "upload_date": obj.get("upload_date"),
            "ai_translated": obj.get("ai_translated"),
            "nb_cd": obj.get("nb_cd"),
            "slug": obj.get("slug"),
            "machine_translated": obj.get("machine_translated"),
            "release": obj.get("release"),
            "comments": obj.get("comments"),
            "legacy_subtitle_id": obj.get("legacy_subtitle_id"),
            "legacy_uploader_id": obj.get("legacy_uploader_id"),
            "uploader": Subtitles200ResponseDataInnerAttributesUploader.from_dict(obj["uploader"]) if obj.get("uploader") is not None else None,
            "feature_details": Subtitles200ResponseDataInnerAttributesFeatureDetails.from_dict(obj["feature_details"]) if obj.get("feature_details") is not None else None,
            "url": obj.get("url"),
            "related_links": [Subtitles200ResponseDataInnerAttributesRelatedLinksInner.from_dict(_item) for _item in obj["related_links"]] if obj.get("related_links") is not None else None,
            "files": [Subtitles200ResponseDataInnerAttributesFilesInner.from_dict(_item) for _item in obj["files"]] if obj.get("files") is not None else None
        })
        return _obj


