# coding: utf-8

"""
    OpenSubtitles API

    Explore Open Subtitles API here

    The version of the OpenAPI document: 1.0.1
    Contact: support@opensubtitles.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from opensubtitles_client.models.translation200_response_data_inner_languages_supported_inner import Translation200ResponseDataInnerLanguagesSupportedInner
from typing import Optional, Set
from typing_extensions import Self

class Translation200ResponseDataInner(BaseModel):
    """
    Translation200ResponseDataInner
    """ # noqa: E501
    name: Optional[StrictStr] = None
    display_name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    pricing: Optional[StrictStr] = None
    reliability: Optional[StrictStr] = None
    price: Optional[Union[StrictFloat, StrictInt]] = None
    languages_supported: Optional[List[Translation200ResponseDataInnerLanguagesSupportedInner]] = None
    __properties: ClassVar[List[str]] = ["name", "display_name", "description", "pricing", "reliability", "price", "languages_supported"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Translation200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in languages_supported (list)
        _items = []
        if self.languages_supported:
            for _item_languages_supported in self.languages_supported:
                if _item_languages_supported:
                    _items.append(_item_languages_supported.to_dict())
            _dict['languages_supported'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Translation200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "display_name": obj.get("display_name"),
            "description": obj.get("description"),
            "pricing": obj.get("pricing"),
            "reliability": obj.get("reliability"),
            "price": obj.get("price"),
            "languages_supported": [Translation200ResponseDataInnerLanguagesSupportedInner.from_dict(_item) for _item in obj["languages_supported"]] if obj.get("languages_supported") is not None else None
        })
        return _obj


