# coding: utf-8

"""
    OpenSubtitles API

    Explore Open Subtitles API here

    The version of the OpenAPI document: 1.0.1
    Contact: support@opensubtitles.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr
from typing import Any, Dict, Optional
from typing_extensions import Annotated

from opensubtitles_client.api_client import ApiClient, RequestSerialized
from opensubtitles_client.api_response import ApiResponse
from opensubtitles_client.rest import RESTResponseType


class AITranslateApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def translate(
        self,
        api: Annotated[StrictStr, Field(description="translation_apis")],
        file: Annotated[StrictStr, Field(description="file contents to translate")],
        translate_to: Annotated[StrictStr, Field(description="language ISO639 translate_from")],
        translate_from: Annotated[Optional[StrictStr], Field(description="language ISO639 translate_from (auto is default)")] = None,
        file_id: Annotated[Optional[StrictInt], Field(description="file_id from /subtitles endpoint")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> object:
        """AI Translate

        **Translate** subtitles using AI from one language to another language.   Credits on user account are needed. [Buy Credits](../open_api.json/paths/~1ai~1credits~1buy/get)  Check following method: [Get AI Translate status](../open_api.json/paths/~1ai~1translate~1{correlation_id}/get)  Method is returning  ``` {   \"status\": \"CREATED\",   \"correlation_id\": \"67eda18f52e11\" } ``` Status possible values:  ``` CREATED     -> Initial state` PENDING     -> procedure is still running COMPLETED   -> remote procedure call is completed and has a result ERROR       -> procedure resulted in an error and is not running anymore TIMEOUT     -> No matching procedure call found before timeout ``` Using `correlation_id` can check status of job using GET 

        :param api: translation_apis (required)
        :type api: str
        :param file: file contents to translate (required)
        :type file: str
        :param translate_to: language ISO639 translate_from (required)
        :type translate_to: str
        :param translate_from: language ISO639 translate_from (auto is default)
        :type translate_from: str
        :param file_id: file_id from /subtitles endpoint
        :type file_id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._translate_serialize(
            api=api,
            file=file,
            translate_to=translate_to,
            translate_from=translate_from,
            file_id=file_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def translate_with_http_info(
        self,
        api: Annotated[StrictStr, Field(description="translation_apis")],
        file: Annotated[StrictStr, Field(description="file contents to translate")],
        translate_to: Annotated[StrictStr, Field(description="language ISO639 translate_from")],
        translate_from: Annotated[Optional[StrictStr], Field(description="language ISO639 translate_from (auto is default)")] = None,
        file_id: Annotated[Optional[StrictInt], Field(description="file_id from /subtitles endpoint")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[object]:
        """AI Translate

        **Translate** subtitles using AI from one language to another language.   Credits on user account are needed. [Buy Credits](../open_api.json/paths/~1ai~1credits~1buy/get)  Check following method: [Get AI Translate status](../open_api.json/paths/~1ai~1translate~1{correlation_id}/get)  Method is returning  ``` {   \"status\": \"CREATED\",   \"correlation_id\": \"67eda18f52e11\" } ``` Status possible values:  ``` CREATED     -> Initial state` PENDING     -> procedure is still running COMPLETED   -> remote procedure call is completed and has a result ERROR       -> procedure resulted in an error and is not running anymore TIMEOUT     -> No matching procedure call found before timeout ``` Using `correlation_id` can check status of job using GET 

        :param api: translation_apis (required)
        :type api: str
        :param file: file contents to translate (required)
        :type file: str
        :param translate_to: language ISO639 translate_from (required)
        :type translate_to: str
        :param translate_from: language ISO639 translate_from (auto is default)
        :type translate_from: str
        :param file_id: file_id from /subtitles endpoint
        :type file_id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._translate_serialize(
            api=api,
            file=file,
            translate_to=translate_to,
            translate_from=translate_from,
            file_id=file_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def translate_without_preload_content(
        self,
        api: Annotated[StrictStr, Field(description="translation_apis")],
        file: Annotated[StrictStr, Field(description="file contents to translate")],
        translate_to: Annotated[StrictStr, Field(description="language ISO639 translate_from")],
        translate_from: Annotated[Optional[StrictStr], Field(description="language ISO639 translate_from (auto is default)")] = None,
        file_id: Annotated[Optional[StrictInt], Field(description="file_id from /subtitles endpoint")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """AI Translate

        **Translate** subtitles using AI from one language to another language.   Credits on user account are needed. [Buy Credits](../open_api.json/paths/~1ai~1credits~1buy/get)  Check following method: [Get AI Translate status](../open_api.json/paths/~1ai~1translate~1{correlation_id}/get)  Method is returning  ``` {   \"status\": \"CREATED\",   \"correlation_id\": \"67eda18f52e11\" } ``` Status possible values:  ``` CREATED     -> Initial state` PENDING     -> procedure is still running COMPLETED   -> remote procedure call is completed and has a result ERROR       -> procedure resulted in an error and is not running anymore TIMEOUT     -> No matching procedure call found before timeout ``` Using `correlation_id` can check status of job using GET 

        :param api: translation_apis (required)
        :type api: str
        :param file: file contents to translate (required)
        :type file: str
        :param translate_to: language ISO639 translate_from (required)
        :type translate_to: str
        :param translate_from: language ISO639 translate_from (auto is default)
        :type translate_from: str
        :param file_id: file_id from /subtitles endpoint
        :type file_id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._translate_serialize(
            api=api,
            file=file,
            translate_to=translate_to,
            translate_from=translate_from,
            file_id=file_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _translate_serialize(
        self,
        api,
        file,
        translate_to,
        translate_from,
        file_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if api is not None:
            
            _query_params.append(('api', api))
            
        if file is not None:
            
            _query_params.append(('file', file))
            
        if translate_from is not None:
            
            _query_params.append(('translate_from', translate_from))
            
        if translate_to is not None:
            
            _query_params.append(('translate_to', translate_to))
            
        if file_id is not None:
            
            _query_params.append(('file_id', file_id))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'multipart/form-data'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'Api-Key', 
            'Bearer'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/ai/translate',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def translate_status(
        self,
        correlation_id: Annotated[StrictStr, Field(description="correlation_id")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """AI Translate status

        Get status of **[translate](..open_api.json/paths/~1ai~1translate/post)** job using `correlation_id` 

        :param correlation_id: correlation_id (required)
        :type correlation_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._translate_status_serialize(
            correlation_id=correlation_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def translate_status_with_http_info(
        self,
        correlation_id: Annotated[StrictStr, Field(description="correlation_id")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """AI Translate status

        Get status of **[translate](..open_api.json/paths/~1ai~1translate/post)** job using `correlation_id` 

        :param correlation_id: correlation_id (required)
        :type correlation_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._translate_status_serialize(
            correlation_id=correlation_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def translate_status_without_preload_content(
        self,
        correlation_id: Annotated[StrictStr, Field(description="correlation_id")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """AI Translate status

        Get status of **[translate](..open_api.json/paths/~1ai~1translate/post)** job using `correlation_id` 

        :param correlation_id: correlation_id (required)
        :type correlation_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._translate_status_serialize(
            correlation_id=correlation_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _translate_status_serialize(
        self,
        correlation_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if correlation_id is not None:
            _path_params['correlation_id'] = correlation_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter




        # authentication setting
        _auth_settings: List[str] = [
            'Api-Key', 
            'Bearer'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/ai/translate/{correlation_id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


