# coding: utf-8

"""
    OpenSubtitles API

    Explore Open Subtitles API here

    The version of the OpenAPI document: 1.0.1
    Contact: support@opensubtitles.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictInt, StrictStr
from typing import Optional
from typing_extensions import Annotated
from opensubtitles_client.models.features200_response import Features200Response

from opensubtitles_client.api_client import ApiClient, RequestSerialized
from opensubtitles_client.api_response import ApiResponse
from opensubtitles_client.rest import RESTResponseType


class FeaturesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def features(
        self,
        query: Annotated[Optional[Annotated[str, Field(min_length=3, strict=True)]], Field(description="query to search, release/file name accepted")] = None,
        type: Annotated[Optional[StrictStr], Field(description="empty to list all or **movie**, **tvshow** or **episode**.")] = None,
        feature_id: Annotated[Optional[StrictInt], Field(description="opensubtitles **feature_id**")] = None,
        imdb_id: Annotated[Optional[StrictStr], Field(description="IMDB ID, delete leading zeroes")] = None,
        tmdb_id: Annotated[Optional[StrictStr], Field(description="TheMovieDB ID - combine with type to avoid errors")] = None,
        year: Annotated[Optional[StrictInt], Field(description="Filter by year. Can only be used in combination with a query")] = None,
        user_agent: Annotated[Optional[StrictStr], Field(description="<<{{APP_NAME}} v{{APP_VERSION}}>>")] = None,
        query_match: Annotated[Optional[StrictStr], Field(description="Type of matching applied to the query: **start** (default), **word**, **exact**  ")] = None,
        full_search: Annotated[Optional[StrictBool], Field(description="Search on original title and title aka (translations) (default false)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> Features200Response:
        """Search for features

        With the \"query\" parameter, search for a Feature from a simple text input. Typically used for a text search or autocomplete.  With an ID, get basic information and subtitles count for a specific title.  With the \"query_match\" you can define the matched applied to the query:   - \"start\" is the default behavior, it will query on the first letter entered to offer suggestions  - \"word\" will return the match on the word, but not always matching the fulll title, for example searching \"roma\" will return \"holiday in roma\"  - \"exact\" will exactly match the title, so here searching for \"roma\" will only return the movie(s) named \"roma\"   With the \"full_search\" you can extend the search to the translations of the title, so \"roma\" will also return \"rome\"   <!-- theme: warning -->  > ### Watch Out! > > If you create an autocomplete, don't set a too small refresh limit, remember you must not go over 40 requests per 10 seconds!

        :param query: query to search, release/file name accepted
        :type query: str
        :param type: empty to list all or **movie**, **tvshow** or **episode**.
        :type type: str
        :param feature_id: opensubtitles **feature_id**
        :type feature_id: int
        :param imdb_id: IMDB ID, delete leading zeroes
        :type imdb_id: str
        :param tmdb_id: TheMovieDB ID - combine with type to avoid errors
        :type tmdb_id: str
        :param year: Filter by year. Can only be used in combination with a query
        :type year: int
        :param user_agent: <<{{APP_NAME}} v{{APP_VERSION}}>>
        :type user_agent: str
        :param query_match: Type of matching applied to the query: **start** (default), **word**, **exact**  
        :type query_match: str
        :param full_search: Search on original title and title aka (translations) (default false)
        :type full_search: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._features_serialize(
            query=query,
            type=type,
            feature_id=feature_id,
            imdb_id=imdb_id,
            tmdb_id=tmdb_id,
            year=year,
            user_agent=user_agent,
            query_match=query_match,
            full_search=full_search,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Features200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def features_with_http_info(
        self,
        query: Annotated[Optional[Annotated[str, Field(min_length=3, strict=True)]], Field(description="query to search, release/file name accepted")] = None,
        type: Annotated[Optional[StrictStr], Field(description="empty to list all or **movie**, **tvshow** or **episode**.")] = None,
        feature_id: Annotated[Optional[StrictInt], Field(description="opensubtitles **feature_id**")] = None,
        imdb_id: Annotated[Optional[StrictStr], Field(description="IMDB ID, delete leading zeroes")] = None,
        tmdb_id: Annotated[Optional[StrictStr], Field(description="TheMovieDB ID - combine with type to avoid errors")] = None,
        year: Annotated[Optional[StrictInt], Field(description="Filter by year. Can only be used in combination with a query")] = None,
        user_agent: Annotated[Optional[StrictStr], Field(description="<<{{APP_NAME}} v{{APP_VERSION}}>>")] = None,
        query_match: Annotated[Optional[StrictStr], Field(description="Type of matching applied to the query: **start** (default), **word**, **exact**  ")] = None,
        full_search: Annotated[Optional[StrictBool], Field(description="Search on original title and title aka (translations) (default false)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[Features200Response]:
        """Search for features

        With the \"query\" parameter, search for a Feature from a simple text input. Typically used for a text search or autocomplete.  With an ID, get basic information and subtitles count for a specific title.  With the \"query_match\" you can define the matched applied to the query:   - \"start\" is the default behavior, it will query on the first letter entered to offer suggestions  - \"word\" will return the match on the word, but not always matching the fulll title, for example searching \"roma\" will return \"holiday in roma\"  - \"exact\" will exactly match the title, so here searching for \"roma\" will only return the movie(s) named \"roma\"   With the \"full_search\" you can extend the search to the translations of the title, so \"roma\" will also return \"rome\"   <!-- theme: warning -->  > ### Watch Out! > > If you create an autocomplete, don't set a too small refresh limit, remember you must not go over 40 requests per 10 seconds!

        :param query: query to search, release/file name accepted
        :type query: str
        :param type: empty to list all or **movie**, **tvshow** or **episode**.
        :type type: str
        :param feature_id: opensubtitles **feature_id**
        :type feature_id: int
        :param imdb_id: IMDB ID, delete leading zeroes
        :type imdb_id: str
        :param tmdb_id: TheMovieDB ID - combine with type to avoid errors
        :type tmdb_id: str
        :param year: Filter by year. Can only be used in combination with a query
        :type year: int
        :param user_agent: <<{{APP_NAME}} v{{APP_VERSION}}>>
        :type user_agent: str
        :param query_match: Type of matching applied to the query: **start** (default), **word**, **exact**  
        :type query_match: str
        :param full_search: Search on original title and title aka (translations) (default false)
        :type full_search: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._features_serialize(
            query=query,
            type=type,
            feature_id=feature_id,
            imdb_id=imdb_id,
            tmdb_id=tmdb_id,
            year=year,
            user_agent=user_agent,
            query_match=query_match,
            full_search=full_search,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Features200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def features_without_preload_content(
        self,
        query: Annotated[Optional[Annotated[str, Field(min_length=3, strict=True)]], Field(description="query to search, release/file name accepted")] = None,
        type: Annotated[Optional[StrictStr], Field(description="empty to list all or **movie**, **tvshow** or **episode**.")] = None,
        feature_id: Annotated[Optional[StrictInt], Field(description="opensubtitles **feature_id**")] = None,
        imdb_id: Annotated[Optional[StrictStr], Field(description="IMDB ID, delete leading zeroes")] = None,
        tmdb_id: Annotated[Optional[StrictStr], Field(description="TheMovieDB ID - combine with type to avoid errors")] = None,
        year: Annotated[Optional[StrictInt], Field(description="Filter by year. Can only be used in combination with a query")] = None,
        user_agent: Annotated[Optional[StrictStr], Field(description="<<{{APP_NAME}} v{{APP_VERSION}}>>")] = None,
        query_match: Annotated[Optional[StrictStr], Field(description="Type of matching applied to the query: **start** (default), **word**, **exact**  ")] = None,
        full_search: Annotated[Optional[StrictBool], Field(description="Search on original title and title aka (translations) (default false)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Search for features

        With the \"query\" parameter, search for a Feature from a simple text input. Typically used for a text search or autocomplete.  With an ID, get basic information and subtitles count for a specific title.  With the \"query_match\" you can define the matched applied to the query:   - \"start\" is the default behavior, it will query on the first letter entered to offer suggestions  - \"word\" will return the match on the word, but not always matching the fulll title, for example searching \"roma\" will return \"holiday in roma\"  - \"exact\" will exactly match the title, so here searching for \"roma\" will only return the movie(s) named \"roma\"   With the \"full_search\" you can extend the search to the translations of the title, so \"roma\" will also return \"rome\"   <!-- theme: warning -->  > ### Watch Out! > > If you create an autocomplete, don't set a too small refresh limit, remember you must not go over 40 requests per 10 seconds!

        :param query: query to search, release/file name accepted
        :type query: str
        :param type: empty to list all or **movie**, **tvshow** or **episode**.
        :type type: str
        :param feature_id: opensubtitles **feature_id**
        :type feature_id: int
        :param imdb_id: IMDB ID, delete leading zeroes
        :type imdb_id: str
        :param tmdb_id: TheMovieDB ID - combine with type to avoid errors
        :type tmdb_id: str
        :param year: Filter by year. Can only be used in combination with a query
        :type year: int
        :param user_agent: <<{{APP_NAME}} v{{APP_VERSION}}>>
        :type user_agent: str
        :param query_match: Type of matching applied to the query: **start** (default), **word**, **exact**  
        :type query_match: str
        :param full_search: Search on original title and title aka (translations) (default false)
        :type full_search: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._features_serialize(
            query=query,
            type=type,
            feature_id=feature_id,
            imdb_id=imdb_id,
            tmdb_id=tmdb_id,
            year=year,
            user_agent=user_agent,
            query_match=query_match,
            full_search=full_search,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Features200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _features_serialize(
        self,
        query,
        type,
        feature_id,
        imdb_id,
        tmdb_id,
        year,
        user_agent,
        query_match,
        full_search,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if query is not None:
            
            _query_params.append(('query', query))
            
        if type is not None:
            
            _query_params.append(('type', type))
            
        if feature_id is not None:
            
            _query_params.append(('feature_id', feature_id))
            
        if imdb_id is not None:
            
            _query_params.append(('imdb_id', imdb_id))
            
        if tmdb_id is not None:
            
            _query_params.append(('tmdb_id', tmdb_id))
            
        if year is not None:
            
            _query_params.append(('year', year))
            
        if query_match is not None:
            
            _query_params.append(('query_match', query_match))
            
        if full_search is not None:
            
            _query_params.append(('full_search', full_search))
            
        # process the header parameters
        if user_agent is not None:
            _header_params['User-Agent'] = user_agent
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'Api-Key'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/features',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


